server:
  port: 8080
spring:
  application:
    name: lolisite-gateway
  cloud:
    consul: #Consul服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
